apiVersion: v1
kind: Pod
metadata:
  name: myapp-liveness
spec:
  containers:
    - name: myapp-container
      image: myapp-image
      livenessProbe:
        # Prompt: Define liveness probe settings here
