apiVersion: v1
kind: Pod
metadata:
  name: myapp-volumes
spec:
  containers:
    - name: myapp-container
      image: myapp-image
      volumeMounts:
        - name: myapp-volume
          mountPath: /app/data
          # Prompt: Define volume mounts here
  volumes:
    - name: myapp-volume
      # Prompt: Define volume settings here
