apiVersion: v1
kind: Pod
metadata:
  name: myapp-secret-env
spec:
  containers:
    - name: myapp-container
      image: myapp-image
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: password
      # Prompt: Define environment variables sourced from a secret here
