apiVersion: batch/v1
kind: Job
metadata:
  name: myapp-job
spec:
  template:
    spec:
      containers:
        - name: myapp-container
          image: myapp-image
          # Prompt: Define command or script to run in the job here
      restartPolicy: Never
