apiVersion: v1
kind: Pod
metadata:
  name: myapp-resources
spec:
  containers:
    - name: myapp-container
      image: myapp-image
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
      # Prompt: Define resource requests and limits here
