apiVersion: v1
kind: Pod
metadata:
  name: myapp-readiness
spec:
  containers:
    - name: myapp-container
      image: myapp-image
      readinessProbe:
        # Prompt: Define readiness probe settings here
